name: my_app
description: >- 
  A new Flutter project related to tourism
  Sample app from "Adding interactivity":
  https://docs.flutter.dev/ui/interactivity.

version: 1.0.0+1

environment:
  sdk: ^3.6.0
# resolution: workspace

# workspace:  
#   - packages/helper
#   - packages/client_package
#   - packages/server_package  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # url_launcher: ^6.2.6
  # open_file: ^3.5.10
  # file_picker: ^9.2.2
  # carousel_slider: ^4.2.1

  dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/lake.jpg
    - assets/images/profile.jpg
    - assets/images/banner.jpg
    - assets/images/news_logo.jpeg
    # - assets/images/sport/explore.jpeg

    # - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package