name: my_app
description: "A new Flutter Layout Demo Project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  
  #esewa dependency
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  esewa_flutter: ^2.0.0
  
  file_picker: ^10.0.0
  http: ^1.3.0
  open_file: ^3.5.10
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  sqflite: ^2.4.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.2.5
 
  #for phone call



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/images/lake.jpg
    - assets/images/banner.jpg
    - assets/images/news_logo.jpeg
    - assets/weather.json
    
    # - assets/images/sport/explore.jpeg

    # - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package